### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by disteph**
- Completed the fix for #227 about interpolant for problems that are unsat before assumptions (should be false_term even if there are no assumptions).
- In the API for `check_context_with_model`, removed the check that the terms should have values in the model; it's ok if they don't: when asking for their values, the default ones will be given and that's ok.
- In the same API function, added a call to `context_clear_unsat(ctx)` if status was previously unsat.
- When Yices clears a SAT status, it should remove the assumptions just like it does when clearing an UNSAT status.

### CODE REVIEW

**Comment by disteph** [comment]
I assume I shouldn't be worried about the failed Travis CI?

**Comment by BrunoDutertre** [comment]
The make check fails on travis (timeout on two benchmarks). The same thing
happens to me on the ``mcsat-assumptions``  branch so the timeouts are unrelated
to your pull request. I'll let @dddejan push the button if he's OK with it.

**Comment by dddejan** [comment]
I need to cleanup some stuff, no worries about the CI failures.

**Comment by dddejan** [comment]
@disteph check if my changes work for you. there are many corner cases it turns out.

**Pull request merged**
