### PR TITLE
Mcsat bv

### PR DESCRIPTION
**Pull request by disteph**
New bv-arithmetic reasoner and minor improvement of the extract-concat reasoner.
The former understands conflicting literals whose terms can have arbitrary nestings of linear bitvector polynomials, extractions and concatenations, as long as the conflict variable appears once.
Aggressive normalisation mechanisms are used to try and shoe-horn the literals into that fragment.
Similar normalisation mechanisms are now also used in the extract-concat reasoner, so that it applies more often, thereby improving it a bit.
Found 1 bug in the run over the 32K SMTLib problems, due to a BV64_POLY over BV64_POLY not being flattened.

### CODE REVIEW

**Comment by disteph** [comment]
Also fixes #142 #143 #145

**Comment by dddejan** [comment]
benchmarks/brummayerbiere3/maxandminor008.smt2
yices-smt2: mcsat/bv/explain/arith_norm.c:556: arith_normalise_upto: Assertion `mono
m[i] == NULL_TERM || (term_kind(terms, monom[i]) != BV_POLY && term_kind(terms, mono
m[i]) != BV64_POLY )' failed.


benchmarks/bruttomesso/simple_processor/simple_processors_006_004_0004.smt2 yices-smt2: ./mcsat/trail.h:175: trail_get_value: Assertion `trail_has_value(trail, var)' failed.
Command exited with non-zero status 21

benchmarks/brummayerbiere3/maxandminor016.smt2
yices-smt2: mcsat/bv/explain/arith_norm.c:556: arith_normalise_upto: Assertion `mono
m[i] == NULL_TERM || (term_kind(terms, monom[i]) != BV_POLY && term_kind(terms, mono
m[i]) != BV64_POLY )' failed.

benchmarks/brummayerbiere3/minandmaxor008.smt2                              yices-smt2: mcsat/bv/explain/arith_norm.c:556: arith_normalise_upto: Assertion `mono
m[i] == NULL_TERM || (term_kind(terms, monom[i]) != BV_POLY && term_kind(terms, mono
m[i]) != BV64_POLY )' failed.
Command exited with non-zero status 21

**Comment by disteph** [comment]
benchmarks/brummayerbiere3/maxandminor008.smt2
benchmarks/brummayerbiere3/maxandminor016.smt2
benchmarks/brummayerbiere3/minandmaxor008.smt2
trigger the the extra assert thta I was talking about above, to reveal cases where the following invariant is broken: arguments of a BV_POLY are not BV_POLY. Bruno knows the invariant doesn't hold in corner cases. I'm waiting to see if we plan to restore this invariant or if I should try and make my code robust to that invariant not holding.

For benchmarks/bruttomesso/simple_processor/simple_processors_006_004_0004.smt2, I'll have a look now.

**Comment by disteph** [comment]
OK, I think it's good for merging

**Comment by dddejan** [comment]
I'll run some check and will merge later.

**Comment by dddejan** [comment]
Here is a small bencmark that fails https://gist.github.com/dddejan/c1a53ae3b360bc94920ac39d0efc63e4

**Comment by disteph** [comment]
OK, I've fixed those! Should be good now (I know, I said that a million times already).

**Comment by dddejan** [comment]
There are some more issues, but I will add them after the merge.

**Pull request merged**
