### PR TITLE
Support big endian architectures

### PR DESCRIPTION
**Pull request by jamesjer**
I found the little endian restriction on yices while preparing to build libpoly 0.1.8 and yices 2.6.2 for Fedora.  We build for s390x, so big endian support is important.  With this patch, the s390x build passes all tests.

### CODE REVIEW

**Comment by ianamason** [comment]
@jamesjer  do you actually have access to a big endian machine? The main reason we balked
at supporting it was that we had no way of testing it.

**Comment by jamesjer** [comment]
Yes, I do have access to an s390x machine running Fedora Linux.

**Comment by ianamason** [comment]
And `make check` succeeds on it with your changes?

**Comment by jamesjer** [comment]
Yes, it does.  All tests passed.

**Comment by ianamason** [comment]
Excellent. I thought our new implementation of rationals was a little sensitive to the endianness, because we steal a bit there somewhere.  Would you be able to run some tests and attach the output?  If yes, I will get back to you with the actual instructions.

**Comment by jamesjer** [comment]
Absolutely.  Let me know what you would like me to do.

**Comment by ianamason** [comment]
So if you do a 
```
make test
```
This will build all the unit tests and the associated binaries will end up in 
```
yices2/build/<arch-mode>/bin/
```
If you do 
```
./build/<arch-mode>/bin/test_rationals2 > test_rationals.jj
./build/<arch-mode>/bin/test_rationals2 > test_rationals2.jj
./build/<arch-mode>/bin/test_rational_conversions > test_rational_conversions.jj
./build/<arch-mode>/bin/test_rational_divrem > test_rational_devrem.jj
./build/<arch-mode>/bin/test_rational_hmaps > test_rational_hmaps.jj
```
I would love those files.

**Comment by ianamason** [comment]
You could just mail me a tar ball or zip if you like.
```
iam@csl.sri.com
```
Thanks again, we were hoping for someone with a big endian machine to show up at some stage!

**Comment by jamesjer** [comment]
The -DWORDS_BIGENDIAN flag is not getting passed to the compiler when I run "make test", which is resulting in lots of mayhem.  Let me figure out how that should be done, and then I can get you some test results that actually mean something.

**Comment by ianamason** [comment]
Thanks for the files @jamesjer  every thing checks out just fine. Magic.

I think we can pull this in @BrunoDutertre, wanna click the button?

**Comment by ianamason** [comment]
Ooops I spoke to soon (how surprising). 
```
On line 1005415 
 diff  test_rationals.iam test_rationals.jj
1005415,1005416c1005415
< format error
< r2 = 1889139832988137873278932897/10000000000000000000
---
> r2 = 8
```
Let me see if I can figure out that first.

**Comment by ianamason** [comment]
Bizarre @BrunoDutertre 
little endian:
```
set_from_float_string <8.eee>
format error
r2 = 1889139832988137873278932897/10000000000000000000
```
while big endian:
```
set_from_float_string <8.eee>
r2 = 8
```
I find it hard to believe this is endianess.
```
...
static char* test_strings2[22] = {
  "1.10", "+1.10", "-1.10",
  "100e0", "100e-2", "100e+2",
  "10.6e0", "10.6e-2", "10.6e+2",
  "+10.6e0", "+10.6e-2", "+10.6e+2",
  "-10.6e0", "-10.6e-2", "-10.6e+2",
  "1889139832988.137873278932897e-4", "8.eee",
  "00001893821/000031278781238", "",
  "46878952/46878952", "+46878952/46878952", "-46878952/46878952",
};

...
  printf("\n");
  for (i=0; i<22; i++) {
    printf("set_from_float_string <%s>\n", test_strings2[i]);
    if (q_set_from_float_string(&r2, test_strings2[i]) >= 0) {
      printf("r2 = ");
      q_print(stdout, &r2);
    } else {
      printf("format error\n");
      printf("r2 = ");
      q_print(stdout, &r2);
    }
    printf("\n\n");
  }
```
I think the deviation is on line 797 of src/terms/rationals.c
in the function 
```
static int _o_q_set_from_float_string(rational_t *r, const char *s)
```
the code being:
```
  // check and read exponent
  exponent = 0;
  if (c == 'e' || c == 'E') {
    errno = 0;  // strtol sets errno on error
    exponent = strtol(s, (char **) NULL, 10);
    if (errno != 0){
      retval =  -1;
      goto clean_up;
    }
  }

```
Maybe `strtol`?

**Comment by jamesjer** [comment]
It isn't endianness.  I ran that test on my x86_64 Fedora 31 machine and also get
```
set_from_float_string <8.eee>
r2 = 8
```
I've got glibc 2.30.  What C library produces the "format error" output?

**Comment by ianamason** [comment]
I'm running on a mac. So my guess is this just an Cupertino abberation. I will let Bruno press
the merge button when he gets back from his "rust seminar" @BrunoDutertre.

Thanks a lot for all your help Jerry.

**Comment by BrunoDutertre** [comment]
The format error vs no format error seems to be a linux vs MacOS (maybe BSD) problem
and yes strtol is likely the culprit. That's not too critical so this shouldn't deal our release.
I'll try to investigate and fix it.

And yes, thanks Jerry!. I'll push the merge button in a second.

**Comment by BrunoDutertre** [comment]
On my linux machine:
```
x = strol("eee", NULL, 10);
```
sets x to 0 and does not report an error (``errno`` is 0)

On my mac, the same code sets ``errno`` to EINVAL (22).

But "man strtol" on the Mac says:

```
ERRORS

    [EINVAL]           The value of base is not supported or no conversion could be performed
                              (the last feature is not portable across all platforms).
```

We were warned!

**Pull request merged**
